images:
  plutono: image-repository:image-tag

ingress:
  class: nginx
  hosts:
  - hostName: pl.seed-1.example.com
    secretName: plutono-tls
  # admin : admin base64 encoded
  authSecretName: auth-secret-name
replicas: 1
ports:
  prometheus: 9090
  plutono: 3000

vpaEnabled: false
role: operators
extensions:
  dashboards: ""

sni:
  enabled: false

nodeLocalDNS:
  enabled: false

reversedVPN:
  highAvailabilityEnabled: false
