apiVersion: v1
kind: Namespace
metadata:
  name: planter-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: planter-system
  name: remote-local-setup-registry
  labels: {app: remote-local-setup-registry}
spec:
  replicas: 1
  selector:
    matchLabels: {app: remote-local-setup-registry}
  template:
    metadata:
      labels: {app: remote-local-setup-registry}
    spec:
      tolerations:
      - key: planter.gardener.cloud/type
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        pool: demo-pods
      containers:
      - name: registry
        image: registry
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          trap 'trap - TERM INT EXIT; jobs -p | xargs -r kill; wait' TERM INT EXIT
          apk add coreutils
          (
            RESTART_AT=$(( $(date -d '1 day 0:00' -u +%s) + RANDOM % 3600))
            echo "Restart within 1 hour after the next UTC midnight for garbage collection on: $(date -u --date="@$RESTART_AT")"
            sleep $(( RESTART_AT - $(date -u +%s) ))
            echo "Restarting..."
            kill 1
          ) &
          if [ -d /var/lib/registry/docker ]; then
            registry garbage-collect -m /etc/docker/registry/config.yml
          fi
          registry serve /etc/docker/registry/config.yml &
          wait
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5001
        ports:
        - containerPort: 5001
          name: registry
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry
          subPath: cache
      - name: docker-mirror
        image: registry
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          trap 'trap - TERM INT EXIT; jobs -p | xargs -r kill; wait' TERM INT EXIT
          apk add coreutils
          (
            RESTART_AT=$(( $(date -d '1 day 0:00' -u +%s) + RANDOM % 3600))
            echo "Restart within 1 hour after the next UTC midnight for garbage collection on: $(date -u --date="@$RESTART_AT")"
            sleep $(( RESTART_AT - $(date -u +%s) ))
            echo "Restarting..."
            kill 1
          ) &
          if [ -d /var/lib/registry/docker ]; then
            registry garbage-collect -m /etc/docker/registry/config.yml
          fi
          registry serve /etc/docker/registry/config.yml &
          wait
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5002
        - name: REGISTRY_PROXY_REMOTEURL
          value: https://registry-1.docker.io
        ports:
        - containerPort: 5002
          name: registry
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry
          subPath: docker-mirror
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: {name: registry}
    spec:
      accessModes: [ReadWriteOnce]
      resources: {requests: {storage: 100Gi}}
      volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  namespace: planter-system
  name: registry
  labels: {app: remote-local-setup-registry}
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: registry
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: docker
  selector: {app: remote-local-setup-registry}
  type: ClusterIP
