apiVersion: v1
kind: Namespace
metadata:
  name: planter-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: remote-local-setup-daemonset
  namespace: planter-system
spec:
  selector:
    matchLabels:
      component: remote-local-setup-with-jail
  template:
    metadata:
      labels:
        component: remote-local-setup-with-jail
    spec:
      tolerations:
      - key: planter.gardener.cloud/type
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        pool: demo-pods
      hostPID: true
      containers:
      - name: node-setup
        image: alpine
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          apk add bind-tools
          let i=1
          while true; do
            REGISTRY_SERVICE_IP=$(dig +short registry.planter-system.svc.cluster.local)
            echo "service IP: " $REGISTRY_SERVICE_IP
            if [ -n "$REGISTRY_SERVICE_IP" ]; then
              break
            fi
            sleep $i
            let i=i*2
          done
          sed 's/^  //' <<NSENTER_EOF | xargs -0 nsenter -t 1 -n -m /bin/sh -c
            set -ex
            sysctl -w net.core.wmem_default=$(( 2 * 1024 * 1024 ))
            sysctl -w net.core.rmem_default=$(( 16 * 1024 * 1024 ))
            tail /proc/sys/net/core/*mem*

            mkdir -p /etc/containerd/certs.d/docker.io
            mkdir -p /etc/containerd/certs.d/registry.planter-system.svc.cluster.local:5001
            mkdir -p /etc/containerd/certs.d/registry.planter-system.svc.cluster.local:5002
            cd /etc/containerd/certs.d

            sed 's/^  //' <<"EOF" > docker.io/hosts.toml.tmp
              server = "https://registry-1.docker.io"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5001"] # registry with manually pushed images
                capabilities = ["pull", "resolve"]
                skip_verify = true

              [host."http://$REGISTRY_SERVICE_IP:5002"] # pull through cache for docker.io
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            sed 's/^  //' <<"EOF" > registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp
              server = "http://$REGISTRY_SERVICE_IP:5001"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5001"] # registry with manually pushed images
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            sed 's/^  //' <<"EOF" > registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp
              server = "http://$REGISTRY_SERVICE_IP:5001"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5002"] # pull through cache for docker.io
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            if diff docker.io/hosts.toml.tmp docker.io/hosts.toml &&
               diff registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp registry.planter-system.svc.cluster.local:5001/hosts.toml &&
               diff registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp registry.planter-system.svc.cluster.local:5002/hosts.toml; then
              rm */*.tmp
            else
              mv docker.io/hosts.toml.tmp docker.io/hosts.toml
              mv registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp registry.planter-system.svc.cluster.local:5001/hosts.toml
              mv registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp registry.planter-system.svc.cluster.local:5002/hosts.toml
              systemctl restart containerd.service
            fi
          NSENTER_EOF
          sleep inf &
          wait
        securityContext:
          privileged: true
