apiVersion: v1
kind: Namespace
metadata:
  name: planter-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: remote-local-setup-daemonset
  namespace: planter-system
spec:
  selector:
    matchLabels:
      component: remote-local-setup-with-jail
  template:
    metadata:
      labels:
        component: remote-local-setup-with-jail
    spec:
      tolerations:
      - key: planter.gardener.cloud/type
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        pool: demo-pods
      hostPID: true
      containers:
      - name: node-setup
        image: alpine
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          apk add bind-tools
          let i=1
          while true; do
            REGISTRY_SERVICE_IP=$(dig +short registry.planter-system.svc.cluster.local)
            echo "service IP: " $REGISTRY_SERVICE_IP
            if [ -n "$REGISTRY_SERVICE_IP" ]; then
              break
            fi
            sleep $i
            let i=i*2
            if [ $i -gt 300 ]; then
              echo "failed to resolve registry service IP"
              exit 1
            fi
          done
          sed 's/^  //' <<NSENTER_EOF | xargs -0 nsenter -t 1 -n -m /bin/sh -c
            set -ex
            sysctl -w net.core.wmem_default=$(( 2 * 1024 * 1024 ))
            sysctl -w net.core.rmem_default=$(( 16 * 1024 * 1024 ))
            tail /proc/sys/net/core/*mem*

            mkdir -p /etc/containerd/certs.d/docker.io
            mkdir -p /etc/containerd/certs.d/registry.planter-system.svc.cluster.local:5001
            mkdir -p /etc/containerd/certs.d/registry.planter-system.svc.cluster.local:5002
            cd /etc/containerd/certs.d

            # transparent mirror configuration for docker.io
            sed 's/^  //' <<"EOF" > docker.io/hosts.toml.tmp
              server = "https://registry-1.docker.io"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5001"] # registry with manually pushed images
                capabilities = ["pull", "resolve"]
                skip_verify = true

              [host."http://$REGISTRY_SERVICE_IP:5002"] # pull through cache for docker.io
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            # registry with manually pushed images
            sed 's/^  //' <<"EOF" > registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp
              server = "http://$REGISTRY_SERVICE_IP:5001"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5001"] # registry with manually pushed images
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            # pull through cache for docker.io
            sed 's/^  //' <<"EOF" > registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp
              server = "http://$REGISTRY_SERVICE_IP:5001"
              capabilities = ["pull", "resolve"]

              [host."http://$REGISTRY_SERVICE_IP:5001"] # registry with manually pushed images
                capabilities = ["pull", "resolve"]
                skip_verify = true

              [host."http://$REGISTRY_SERVICE_IP:5002"] # pull through cache for docker.io
                capabilities = ["pull", "resolve"]
                skip_verify = true
            EOF

            if ! grep -F '[plugins."io.containerd.grpc.v1.cri".registry]' /etc/containerd/config.toml; then
              awk '
                /^\[/ {
                  flag=0
                }
                /^\[plugins."io.containerd.grpc.v1.cri".registry.mirrors/ {
                  flag=1
                }
                !flag' /etc/containerd/config.toml > /etc/containerd/config.toml.tmp

              diff -u /etc/containerd/config.toml /etc/containerd/config.toml.tmp || true
              mv /etc/containerd/config.toml.tmp /etc/containerd/config.toml

              cat <<"EOF" >> /etc/containerd/config.toml
            [plugins."io.containerd.grpc.v1.cri".registry]
              config_path = "/etc/containerd/certs.d"
            EOF
              needs_restart=1
            fi

            if [ -n "$needs_restart" ] ||
               ! diff docker.io/hosts.toml.tmp docker.io/hosts.toml ||
               ! diff registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp registry.planter-system.svc.cluster.local:5001/hosts.toml ||
               ! diff registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp registry.planter-system.svc.cluster.local:5002/hosts.toml; then
              mv docker.io/hosts.toml.tmp docker.io/hosts.toml
              mv registry.planter-system.svc.cluster.local:5001/hosts.toml.tmp registry.planter-system.svc.cluster.local:5001/hosts.toml
              mv registry.planter-system.svc.cluster.local:5002/hosts.toml.tmp registry.planter-system.svc.cluster.local:5002/hosts.toml
              systemctl restart containerd.service
            else
              rm */*.tmp
            fi

          NSENTER_EOF
          sleep inf &
          wait
        securityContext:
          privileged: true
