apiVersion: v1
kind: Namespace
metadata:
  name: remote-local-setup-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: remote-local-setup-registry
  name: remote-local-setup-registry
  labels: {app: remote-local-setup-registry}
spec:
  replicas: 1
  selector:
    matchLabels: {app: remote-local-setup-registry}
  template:
    metadata:
      labels: {app: remote-local-setup-registry}
    spec:
      containers:
      - name: registry
        image: registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5001
        ports:
        - containerPort: 5001
          name: registry
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: {name: registry}
    spec:
      accessModes: [ReadWriteOnce]
      resources: {requests: {storage: 20Gi}}
      volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  namespace: remote-local-setup-registry
  name: registry
  labels: {app: remote-local-setup-registry}
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: registry
  selector: {app: remote-local-setup-registry}
  type: ClusterIP
