{
 "title": "Istio Mesh Dashboard",
 "tags": [ "istio" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tcp_service",
    "label": "TCP Service",
    "query": "label_values(istio_tcp_received_bytes_total, destination_service)"
   }
  ]
 },
 "panels": [
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Transfer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(istio_tcp_received_bytes_total{destination_service=~\"$tcp_service\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(istio_tcp_sent_bytes_total{destination_service=~\"$tcp_service\"})",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "connections/second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_connections_opened_total{destination_service=~\"$tcp_service\"}[$__rate_interval]))",
     "legendFormat": "opened"
    },
    {
     "expr": "sum(irate(istio_tcp_connections_closed_total{destination_service=~\"$tcp_service\"}[$__rate_interval]))",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "TCP Workloads per second",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_tcp_received_bytes_total{reporter=\"source\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    },
    {
     "expr": "label_join(sum(rate(istio_tcp_sent_bytes_total{reporter=\"source\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    }
   ]
  },
  {
   "title": "Istio Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Services",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"delete\"}) or max(up * 0))"
      }
     ]
    },
    {
     "title": "Destination Rules",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"delete\"}) or max(up * 0))"
      }
     ]
    },
    {
     "title": "Gateways",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"delete\"}) or max(up * 0))"
      }
     ]
    },
    {
     "title": "Workload Entries",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
     "format": "none",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"delete\"}) or max(up * 0))"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP/GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Request Volume",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
     "format": "ops",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[$__rate_interval])), 0.001)"
      }
     ]
    },
    {
     "title": "Global Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[$__rate_interval])) / sum(rate(istio_requests_total{reporter=\"source\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "4xxs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
     "format": "ops",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\"}[$__rate_interval])) "
      }
     ]
    },
    {
     "title": "5xxs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
     "format": "ops",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[$__rate_interval])) "
      }
     ]
    },
    {
     "title": "HTTP/GRPC Workloads",
     "type": "table-old",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "label_join(sum(rate(istio_requests_total{reporter=\"source\", response_code=\"200\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[$__rate_interval])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace) / sum(rate(istio_requests_total{reporter=\"source\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      }
     ]
    }
   ]
  },
  { "title": "Istio Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Istio Components by Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  }
 ]
}