{
 "title": "Istio Ingress Gateway",
 "tags": [ "istio" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "istio_proxy_pod",
    "query": {
     "query": "container_cpu_usage_seconds_total{container=\"istio-proxy\"}"
    }
   },
   { "name": "istio_proxy_namespace", "query": { "query": "istio_tcp_received_bytes_total" } }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"$istio_proxy_pod\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$istio_proxy_pod\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TCP Received by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_received_bytes_total{pod=~\"$istio_proxy_pod\" }[$__rate_interval])) by(pod)",
     "legendFormat": "{{  pod }} "
    }
   ]
  },
  {
   "title": "TCP Sent by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_sent_bytes_total{pod=~\"$istio_proxy_pod\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{  pod }} "
    }
   ]
  },
  {
   "title": "TCP Received by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_received_bytes_total{pod=~\"$istio_proxy_pod\", namespace=~\"$istio_proxy_namespace\" }[$__rate_interval])) by (namespace)",
     "legendFormat": "{{  namespace }} "
    }
   ]
  },
  {
   "title": "TCP Send by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_tcp_received_bytes_total{pod=~\"$istio_proxy_pod\", namespace=~\"$istio_proxy_namespace\" }[$__rate_interval])) by (namespace)",
     "legendFormat": "{{  namespace }} "
    }
   ]
  }
 ]
}