images:
  alertmanager: image-repository:image-tag
  configmap-reloader: image-repository:image-tag

ingress:
  class: nginx
  hosts:
    - hostName: a.seed-1.example.com
      secretName: plutono-tls
  # admin : admin base64 encoded
  authSecretName: auth-secret-name

emailConfigs: []
replicas: 1
