{
 "title": "Kubernetes Pods",
 "tags": [
  "kubernetes",
  "seed",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "seed,shoot" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{type=~\"$type\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{type=~\"$type\", pod=~\"$pod\"}, container)"
    }
   },
   { "name": "search", "label": "Search" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$pod\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{pod_ip}}"
    },
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "kube_pod_info{pod=\"$pod\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"$pod\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Requests ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"$pod\", container=~\"$container\"}) by (pod)",
     "legendFormat": "Limits ({{pod}})"
    },
    {
     "expr": "sum(rate(container_oom_events_total{pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (pod)",
     "legendFormat": "OOM Events ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The \"Throttle %\" metric shows the percentage of the 100ms time slots where the CPU usage reaches the quota.\n\n0% means the quota is not reached. 100% means the quota is reached in all the 100ms time slots.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$container\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", container=~\"$container\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Requests ({{pod}})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", container=~\"$container\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Limits ({{pod}})"
    },
    {
     "expr": "max(\nrate(container_cpu_cfs_throttled_periods_total{container=~\"$container\",pod=~\"$pod\"}[$__rate_interval])\n/\nrate(container_cpu_cfs_periods_total{container=~\"$container\",pod=~\"$pod\"}[$__rate_interval])\n) by (pod)",
     "legendFormat": "Throttle % ({{pod}})"
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "table",
   "description": "If host_network is true, the pod will not have network I/O metrics.\n\nNote: For pods that use the host network, we cannot collect meaningful network metrics, because the host network includes network traffic from the system services and other pods. Therefore, this dashboard only shows the network traffic for pods which are not in the host network namespace.\n",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(kube_pod_info{pod=~\"$pod\"}) by(pod, host_network)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Note: For pods that use the host network, we cannot collect meaningful network metrics, because the host network includes network traffic from the system services and other pods. Therefore, this dashboard only shows the network traffic for pods which are not in the host network namespace.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received ({{pod}})"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Sent ({{pod}})"
    }
   ]
  },
  {
   "title": "Pod File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$pod\", container=~\"$container\",}) by (pod)",
     "legendFormat": "Current ({{pod}})"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$pod\", image!=\"\"}) by (pod)",
     "legendFormat": "Total ({{pod}})"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{pod_name=~\"$pod\", container_name=~\"$container\"} |~ \"$search\""
    }
   ]
  }
 ]
}