---
apiVersion: v1
kind: Service
metadata:
  name: plutono-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: plutono
    role: {{ .Values.role }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 3000
    protocol: TCP
  selector:
    component: plutono
    role: {{ .Values.role }}
