apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
{{- if semverCompare "< 1.22-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.authSecretName }}
    nginx.ingress.kubernetes.io/auth-type: basic
{{- if eq .Values.role "users" }}
    nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header X-Scope-OrgID user;"
{{- else }}
    nginx.ingress.kubernetes.io/configuration-snippet: "proxy_set_header X-Scope-OrgID operator;"
{{- end }}
  name: plutono-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: plutono
    role: {{ .Values.role }}
spec:
{{- if semverCompare ">= 1.22-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.class }}
{{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          service:
            name: plutono-{{ $.Values.role }}
            port:
              number: {{ required ".ports.plutono is required" $.Values.ports.plutono }}
        path: /
        pathType: Prefix
  {{- end }}
