apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: operatorgrafana
    gardener.cloud/role: monitoring
    networking.gardener.cloud/to-dns: allowed
    role: operator
  name: operatorgrafana
  namespace: some-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: operatorgrafana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
        gardener.cloud/role: monitoring
        networking.gardener.cloud/to-dns: allowed
        role: operator
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_USERS_VIEWERS_CAN_EDIT
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SNAPSHOTS_EXTERNAL_ENABLED
          value: "false"
        - name: GF_ALERTING_ENABLED
          value: "false"
        - name: GF_DATE_FORMATS_DEFAULT_TIMEZONE
          value: "UTC"
        image: "grafana/grafana"
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 400Mi
status: {}
